import type { Card } from "@/lib/types";

export const cardData: Card[] = [
  // money cards
  {
    id: "money-1m-1",
    type: "money",
    name: "1M",
    value: 1,
    image: "1m.png",
  },
  {
    id: "money-1m-2",
    type: "money",
    name: "1M",
    value: 1,
    image: "1m.png",
  },
  {
    id: "money-1m-3",
    type: "money",
    name: "1M",
    value: 1,
    image: "1m.png",
  },
  {
    id: "money-1m-4",
    type: "money",
    name: "1M",
    value: 1,
    image: "1m.png",
  },
  {
    id: "money-1m-5",
    type: "money",
    name: "1M",
    value: 1,
    image: "1m.png",
  },
  {
    id: "money-1m-6",
    type: "money",
    name: "1M",
    value: 1,
    image: "1m.png",
  },

  {
    id: "money-2m-1",
    type: "money",
    name: "2M",
    value: 2,
    image: "2m.png",
  },
  {
    id: "money-2m-2",
    type: "money",
    name: "2M",
    value: 2,
    image: "2m.png",
  },
  {
    id: "money-2m-3",
    type: "money",
    name: "2M",
    value: 2,
    image: "2m.png",
  },
  {
    id: "money-2m-4",
    type: "money",
    name: "2M",
    value: 2,
    image: "2m.png",
  },
  {
    id: "money-2m-5",
    type: "money",
    name: "2M",
    value: 2,
    image: "2m.png",
  },

  {
    id: "money-3m-1",
    type: "money",
    name: "3M",
    value: 3,
    image: "3m.png",
  },
  {
    id: "money-3m-2",
    type: "money",
    name: "3M",
    value: 3,
    image: "3m.png",
  },
  {
    id: "money-3m-3",
    type: "money",
    name: "3M",
    value: 3,
    image: "3m.png",
  },

  {
    id: "money-4m-1",
    type: "money",
    name: "4M",
    value: 4,
    image: "4m.png",
  },
  {
    id: "money-4m-2",
    type: "money",
    name: "4M",
    value: 4,
    image: "4m.png",
  },
  {
    id: "money-4m-3",
    type: "money",
    name: "4M",
    value: 4,
    image: "4m.png",
  },

  {
    id: "money-5m-1",
    type: "money",
    name: "5M",
    value: 5,
    image: "5m.png",
  },
  {
    id: "money-5m-2",
    type: "money",
    name: "5M",
    value: 5,
    image: "5m.png",
  },

  {
    id: "money-10m-1",
    type: "money",
    name: "10M",
    value: 10,
    image: "10m.png",
  },

  // Property cards - Brown
  {
    id: "property-old-kent-road",
    type: "property",
    name: "Old Kent Road",
    value: 1,
    color: "brown",
    rent: { 1: 1, 2: 2 }, // Rent for 1 property, 2 properties
    image: "old-kent-road.png",
  },
  {
    id: "property-whitechapel-road",
    type: "property",
    name: "Whitechapel Road",
    value: 1,
    color: "brown",
    rent: { 1: 1, 2: 2 }, // Rent for 1 property, 2 properties
    image: "whitechapel-road.png",
  },

  // Property cards - Light Blue
  {
    id: "property-euston-road",
    type: "property",
    name: "Euston Road",
    value: 1,
    color: "light blue",
    rent: { 1: 1, 2: 2, 3: 3 }, // Rent for 1, 2, 3 properties
    image: "euston-road.png",
  },
  {
    id: "property-pentonville-road",
    type: "property",
    name: "Pentonville Road",
    value: 1,
    color: "light blue",
    rent: { 1: 1, 2: 2, 3: 3 }, // Rent for 1, 2, 3 properties
    image: "pentonville-road.png",
  },
  {
    id: "property-the-angel-islington",
    type: "property",
    name: "The Angel Islington",
    value: 1,
    color: "light blue",
    rent: { 1: 1, 2: 2, 3: 3 }, // Rent for 1, 2, 3 properties
    image: "the-angel-islington.png",
  },

  // Property cards - Pink
  {
    id: "property-pall-mall",
    type: "property",
    name: "Pall Mall",
    value: 2,
    color: "pink",
    rent: { 1: 1, 2: 2, 3: 4 }, // Rent for 1, 2, 3 properties
    image: "pall-mall.png",
  },
  {
    id: "property-whitehall",
    type: "property",
    name: "Whitehall",
    value: 2,
    color: "pink",
    rent: { 1: 1, 2: 2, 3: 4 }, // Rent for 1, 2, 3 properties
    image: "whitehall.png",
  },
  {
    id: "property-northumberland-drive",
    type: "property",
    name: "Northumberland Drive",
    value: 2,
    color: "pink",
    rent: { 1: 1, 2: 2, 3: 4 }, // Rent for 1, 2, 3 properties
    image: "northumberland-drive.png",
  },

  // Property cards - Orange
  {
    id: "property-vine-street",
    type: "property",
    name: "Vine Street",
    value: 2,
    color: "orange",
    rent: { 1: 1, 2: 3, 3: 5 }, // Rent for 1, 2, 3 properties
    image: "vine-street.png",
  },
  {
    id: "property-bow-street",
    type: "property",
    name: "Bow Street",
    value: 2,
    color: "orange",
    rent: { 1: 1, 2: 3, 3: 5 }, // Rent for 1, 2, 3 properties
    image: "bow-street.png",
  },
  {
    id: "property-marlborough-street",
    type: "property",
    name: "Marlborough Street",
    value: 2,
    color: "orange",
    rent: { 1: 1, 2: 3, 3: 5 }, // Rent for 1, 2, 3 properties
    image: "marlborough-street.png",
  },

  // Property cards - Red
  {
    id: "property-strand",
    type: "property",
    name: "Strand",
    value: 3,
    color: "red",
    rent: { 1: 2, 2: 3, 3: 6 }, // Rent for 1, 2, 3 properties
    image: "strand.png",
  },
  {
    id: "property-fleet-street",
    type: "property",
    name: "Fleet Street",
    value: 3,
    color: "red",
    rent: { 1: 2, 2: 3, 3: 6 }, // Rent for 1, 2, 3 properties
    image: "fleet-street.png",
  },
  {
    id: "property-trafalgar-square",
    type: "property",
    name: "Trafalgar Square",
    value: 3,
    color: "red",
    rent: { 1: 2, 2: 3, 3: 6 }, // Rent for 1, 2, 3 properties
    image: "trafalgar-square.png",
  },

  // Property cards - Yellow
  {
    id: "property-piccadilly",
    type: "property",
    name: "Piccadilly",
    value: 3,
    color: "yellow",
    rent: { 1: 2, 2: 4, 3: 6 }, // Rent for 1, 2, 3 properties
    image: "piccadilly.png",
  },
  {
    id: "property-leicester-square",
    type: "property",
    name: "Leicester Square",
    value: 3,
    color: "yellow",
    rent: { 1: 2, 2: 4, 3: 6 }, // Rent for 1, 2, 3 properties
    image: "leicester-square.png",
  },
  {
    id: "property-coventry-street",
    type: "property",
    name: "Coventry Street",
    value: 3,
    color: "yellow",
    rent: { 1: 2, 2: 4, 3: 6 }, // Rent for 1, 2, 3 properties
    image: "coventry-street.png",
  },

  // Property cards - Green
  {
    id: "property-bond-street",
    type: "property",
    name: "Bond Street",
    value: 4,
    color: "green",
    rent: { 1: 2, 2: 4, 3: 7 }, // Rent for 1, 2, 3 properties
    image: "bond-street.png",
  },
  {
    id: "property-oxford-street",
    type: "property",
    name: "Oxford Street",
    value: 4,
    color: "green",
    rent: { 1: 2, 2: 4, 3: 7 }, // Rent for 1, 2, 3 properties
    image: "oxford-street.png",
  },
  {
    id: "property-regent-street",
    type: "property",
    name: "Regent Street",
    value: 4,
    color: "green",
    rent: { 1: 2, 2: 4, 3: 7 }, // Rent for 1, 2, 3 properties
    image: "regent-street.png",
  },

  // Property cards - Dark Blue
  {
    id: "property-park-lane",
    type: "property",
    name: "Park Lane",
    value: 4,
    color: "dark blue",
    rent: { 1: 3, 2: 8 }, // Rent for 1, 2 properties
    image: "park-lane.png",
  },
  {
    id: "property-mayfair",
    type: "property",
    name: "Mayfair",
    value: 4,
    color: "dark blue",
    rent: { 1: 3, 2: 8 }, // Rent for 1, 2 properties
    image: "mayfair.png",
  },

  // Property cards - Black
  {
    id: "station-kings-cross-station",
    type: "station",
    name: "King's Cross Station",
    value: 2,
    color: "black",
    rent: { 1: 1, 2: 2, 3: 3, 4: 4 }, // Rent for 1, 2 properties
    image: "kings-cross-station.png",
  },
  {
    id: "station-marylebone-station",
    type: "station",
    name: "Marylebone Station",
    value: 2,
    color: "black",
    rent: { 1: 1, 2: 2, 3: 3, 4: 4 },
    image: "marylebone-station.png",
  },
  {
    id: "station-fenchurch-street-station",
    type: "station",
    name: "Fenchurch St. Station",
    value: 2,
    color: "black",
    rent: { 1: 1, 2: 2, 3: 3, 4: 4 },
    image: "fenchurch-st-station.png",
  },
  {
    id: "station-liverpool-street-station",
    type: "station",
    name: "Liverpool St. Station",
    value: 2,
    color: "black",
    rent: { 1: 1, 2: 2, 3: 3, 4: 4 },
    image: "liverpool-st-station.png",
  },
  {
    id: "utilities-electric-company",
    type: "utility",
    name: "Electric Company",
    value: 2,
    color: "mint",
    rent: { 1: 1, 2: 2 }, // Rent for 1, 2 properties
    image: "electric-company.png",
  },
  {
    id: "utilities-water-works",
    type: "utility",
    name: "Water Works",
    value: 2,
    color: "mint",
    rent: { 1: 1, 2: 2 }, // Rent for 1, 2 properties
    image: "water-works.png",
  },

  // Wildcards
  {
    id: "wildcard-orange-pink-1",
    type: "wildcard",
    name: "Wild Property",
    value: 2,
    color: "orange",
    secondaryColor: "pink",
    image: "orange-pink-wildcard.png",
  },
  {
    id: "wildcard-orange-pink-2",
    type: "wildcard",
    name: "Wild Property",
    value: 2,
    color: "orange",
    secondaryColor: "pink",
    image: "orange-pink-wildcard.png",
  },
  {
    id: "wildcard-red-yellow-1",
    type: "wildcard",
    name: "Wild Property",
    value: 3,
    color: "yellow",
    secondaryColor: "red",
    image: "yellow-red-wildcard.png",
  },
  {
    id: "wildcard-red-yellow-2",
    type: "wildcard",
    name: "Wild Property",
    value: 3,
    color: "yellow",
    secondaryColor: "red",
    image: "yellow-red-wildcard.png",
  },
  {
    id: "wildcard-dark-blue-green-1",
    type: "wildcard",
    name: "Wild Property",
    value: 4,
    color: "green",
    secondaryColor: "dark blue",
    image: "green-blue-wildcard.png",
  },
  {
    id: "wildcard-black-green-1",
    type: "wildcard",
    name: "Wild Property",
    value: 4,
    color: "black",
    secondaryColor: "green",
    image: "black-green-wildcard.png",
  },
  {
    id: "wildcard-black-light-blue-1",
    type: "wildcard",
    name: "Wild Property",
    value: 2,
    color: "black",
    secondaryColor: "light blue",
    image: "black-light-blue-wildcard.png",
  },
  {
    id: "wildcard-black-mint-1",
    type: "wildcard",
    name: "Wild Property",
    value: 2,
    color: "black",
    secondaryColor: "mint",
    image: "black-mint-wildcard.png",
  },
  {
    id: "wildcard-brown-light-blue-1",
    type: "wildcard",
    name: "Wild Property",
    value: 1,
    color: "brown",
    secondaryColor: "light blue",
    image: "brown-light-blue-wildcard.png",
  },

  {
    id: "wildcard-any-1",
    type: "wildcard",
    name: "Any Color Wildcard",
    value: 0,
    color: "any",
    image: "wild-property.png",
  },
  {
    id: "wildcard-any-2",
    type: "wildcard",
    name: "Any Color Wildcard",
    value: 0,
    color: "any",
    image: "wild-property.png",
  },

  // Action cards
  {
    id: "action-debt-collector-1",
    type: "action",
    name: "Debt Collector",
    value: 3,
    actionType: "debt-collector",
    image: "debt-collector.png",
  },
  {
    id: "action-debt-collector-2",
    type: "action",
    name: "Debt Collector",
    value: 3,
    actionType: "debt-collector",
    image: "debt-collector.png",
  },
  {
    id: "action-debt-collector-3",
    type: "action",
    name: "Debt Collector",
    value: 3,
    actionType: "debt-collector",
    image: "debt-collector.png",
  },
  {
    id: "action-birthday-1",
    type: "action",
    name: "It's My Birthday",
    value: 2,
    actionType: "birthday",
    image: "birthday.png",
  },
  {
    id: "action-birthday-2",
    type: "action",
    name: "It's My Birthday",
    value: 2,
    actionType: "birthday",
    image: "birthday.png",
  },
  {
    id: "action-pass-go-1",
    type: "action",
    name: "Pass Go",
    value: 1,
    actionType: "pass-go",
    image: "pass-go.png",
  },
  {
    id: "action-pass-go-2",
    type: "action",
    name: "Pass Go",
    value: 1,
    actionType: "pass-go",
    image: "pass-go.png",
  },
  {
    id: "action-pass-go-3",
    type: "action",
    name: "Pass Go",
    value: 1,
    actionType: "pass-go",
    image: "pass-go.png",
  },
  {
    id: "action-pass-go-4",
    type: "action",
    name: "Pass Go",
    value: 1,
    actionType: "pass-go",
    image: "pass-go.png",
  },
  {
    id: "action-pass-go-5",
    type: "action",
    name: "Pass Go",
    value: 1,
    actionType: "pass-go",
    image: "pass-go.png",
  },
  {
    id: "action-pass-go-6",
    type: "action",
    name: "Pass Go",
    value: 1,
    actionType: "pass-go",
    image: "pass-go.png",
  },
  {
    id: "action-pass-go-7",
    type: "action",
    name: "Pass Go",
    value: 1,
    actionType: "pass-go",
    image: "pass-go.png",
  },
  {
    id: "action-pass-go-8",
    type: "action",
    name: "Pass Go",
    value: 1,
    actionType: "pass-go",
    image: "pass-go.png",
  },
  {
    id: "action-pass-go-9",
    type: "action",
    name: "Pass Go",
    value: 1,
    actionType: "pass-go",
    image: "pass-go.png",
  },
  {
    id: "action-pass-go-10",
    type: "action",
    name: "Pass Go",
    value: 1,
    actionType: "pass-go",
    image: "pass-go.png",
  },
  {
    id: "action-deal-breaker-1",
    type: "action",
    name: "Deal Breaker",
    value: 5,
    actionType: "deal-breaker",
    image: "deal-breaker.png",
  },
  {
    id: "action-deal-breaker-2",
    type: "action",
    name: "Deal Breaker",
    value: 5,
    actionType: "deal-breaker",
    image: "deal-breaker.png",
  },
  {
    id: "action-sly-deal-1",
    type: "action",
    name: "Sly Deal",
    value: 3,
    actionType: "sly-deal",
    image: "sly-deal.png",
  },
  {
    id: "action-sly-deal-2",
    type: "action",
    name: "Sly Deal",
    value: 3,
    actionType: "sly-deal",
    image: "sly-deal.png",
  },
  {
    id: "action-sly-deal-3",
    type: "action",
    name: "Sly Deal",
    value: 3,
    actionType: "sly-deal",
    image: "sly-deal.png",
  },
  {
    id: "action-forced-deal-1",
    type: "action",
    name: "Forced Deal",
    value: 3,
    actionType: "forced-deal",
    image: "forced-deal.png",
  },
  {
    id: "action-forced-deal-2",
    type: "action",
    name: "Forced Deal",
    value: 3,
    actionType: "forced-deal",
    image: "forced-deal.png",
  },
  {
    id: "action-forced-deal-3",
    type: "action",
    name: "Forced Deal",
    value: 3,
    actionType: "forced-deal",
    image: "forced-deal.png",
  },
  {
    id: "action-just-say-no-1",
    type: "action",
    name: "Just Say No",
    value: 4,
    actionType: "just-say-no",
    image: "just-say-no.png",
  },
  {
    id: "action-just-say-no-2",
    type: "action",
    name: "Just Say No",
    value: 4,
    actionType: "just-say-no",
    image: "just-say-no.png",
  },
  {
    id: "action-just-say-no-3",
    type: "action",
    name: "Just Say No",
    value: 4,
    actionType: "just-say-no",
    image: "just-say-no.png",
  },
  {
    id: "action-rent-brown-light-blue-1",
    type: "action",
    name: "Rent: Brown/Light Blue",
    value: 1,
    actionType: "rent",
    color: "brown",
    secondaryColor: "light blue",
    image: "rent-brown-or-light-blue.png",
  },
  {
    id: "action-rent-brown-light-blue-2",
    type: "action",
    name: "Rent: Brown/Light Blue",
    value: 1,
    actionType: "rent",
    color: "brown",
    secondaryColor: "light blue",
    image: "rent-brown-or-light-blue.png",
  },
  {
    id: "action-rent-pink-orange-1",
    type: "action",
    name: "Rent: Pink/Orange",
    value: 1,
    actionType: "rent",
    color: "pink",
    secondaryColor: "orange",
    image: "rent-pink-or-orange.png",
  },
  {
    id: "action-rent-pink-orange-2",
    type: "action",
    name: "Rent: Pink/Orange",
    value: 1,
    actionType: "rent",
    color: "pink",
    secondaryColor: "orange",
    image: "rent-pink-or-orange.png",
  },
  {
    id: "action-rent-red-yellow-1",
    type: "action",
    name: "Rent: Red/Yellow",
    value: 1,
    actionType: "rent",
    color: "red",
    secondaryColor: "yellow",
    image: "rent-red-or-yellow.png",
  },
  {
    id: "action-rent-red-yellow-2",
    type: "action",
    name: "Rent: Red/Yellow",
    value: 1,
    actionType: "rent",
    color: "red",
    secondaryColor: "yellow",
    image: "rent-red-or-yellow.png",
  },
  {
    id: "action-rent-dark-blue-green-1",
    type: "action",
    name: "Rent: Dark Blue/Green",
    value: 1,
    actionType: "rent",
    color: "dark blue",
    secondaryColor: "green",
    image: "rent-dark-blue-or-green.png",
  },
  {
    id: "action-rent-dark-blue-green-2",
    type: "action",
    name: "Rent: Dark Blue/Green",
    value: 1,
    actionType: "rent",
    color: "dark blue",
    secondaryColor: "green",
    image: "rent-dark-blue-or-green.png",
  },
  {
    id: "action-rent-mint-black-1",
    type: "action",
    name: "Rent: Mint/Black",
    value: 1,
    actionType: "rent",
    color: "mint",
    secondaryColor: "black",
    image: "rent-mint-or-black.png",
  },
  {
    id: "action-rent-mint-black-2",
    type: "action",
    name: "Rent: Mint/Black",
    value: 1,
    actionType: "rent",
    color: "mint",
    secondaryColor: "black",
    image: "rent-mint-or-black.png",
  },
  {
    id: "action-any-color-1",
    type: "action",
    name: "Rent: Any",
    value: 3,
    actionType: "rent",
    color: "any",
    image: "rent-any-colour.png",
  },
  {
    id: "action-any-color-2",
    type: "action",
    name: "Rent: Any",
    value: 3,
    actionType: "rent",
    color: "any",
    image: "rent-any-colour.png",
  },
  {
    id: "action-any-color-3",
    type: "action",
    name: "Rent: Any",
    value: 3,
    actionType: "rent",
    color: "any",
    image: "rent-any-colour.png",
  },

  // House and Hotel cards
];
