import type { Card } from "@/lib/types";

export const cardData: Card[] = [
  // money cards
  {
    id: "money-1m-1",
    type: "money",
    name: "1M",
    value: 1,
    image: "/cards/1m.png",
  },
  {
    id: "money-1m-2",
    type: "money",
    name: "1M",
    value: 1,
    image: "/cards/1m.png",
  },
  {
    id: "money-1m-3",
    type: "money",
    name: "1M",
    value: 1,
    image: "/cards/1m.png",
  },
  {
    id: "money-1m-4",
    type: "money",
    name: "1M",
    value: 1,
    image: "/cards/1m.png",
  },
  {
    id: "money-1m-5",
    type: "money",
    name: "1M",
    value: 1,
    image: "/cards/1m.png",
  },
  {
    id: "money-1m-6",
    type: "money",
    name: "1M",
    value: 1,
    image: "/cards/1m.png",
  },
  {
    id: "money-2m-1",
    type: "money",
    name: "2M",
    value: 2,
    image: "/cards/2m.png",
  },
  {
    id: "money-2m-2",
    type: "money",
    name: "2M",
    value: 2,
    image: "/cards/2m.png",
  },
  {
    id: "money-2m-3",
    type: "money",
    name: "2M",
    value: 2,
    image: "/cards/2m.png",
  },
  {
    id: "money-2m-4",
    type: "money",
    name: "2M",
    value: 2,
    image: "/cards/2m.png",
  },
  {
    id: "money-2m-5",
    type: "money",
    name: "2M",
    value: 2,
    image: "/cards/2m.png",
  },
  {
    id: "money-3m-1",
    type: "money",
    name: "3M",
    value: 3,
    image: "/cards/3m.png",
  },
  {
    id: "money-3m-2",
    type: "money",
    name: "3M",
    value: 3,
    image: "/cards/3m.png",
  },
  {
    id: "money-3m-3",
    type: "money",
    name: "3M",
    value: 3,
    image: "/cards/3m.png",
  },
  {
    id: "money-4m-1",
    type: "money",
    name: "4M",
    value: 4,
    image: "/cards/4m.png",
  },
  {
    id: "money-4m-2",
    type: "money",
    name: "4M",
    value: 4,
    image: "/cards/4m.png",
  },
  {
    id: "money-4m-3",
    type: "money",
    name: "4M",
    value: 4,
    image: "/cards/4m.png",
  },
  {
    id: "money-5m-1",
    type: "money",
    name: "5M",
    value: 5,
    image: "/cards/5m.png",
  },
  {
    id: "money-5m-2",
    type: "money",
    name: "5M",
    value: 5,
    image: "/cards/5m.png",
  },
  {
    id: "money-10m-1",
    type: "money",
    name: "10M",
    value: 10,
    image: "/cards/10m.png",
  },
  // Property cards - Brown
  {
    id: "property-old-kent-road",
    type: "property",
    name: "Old Kent Road",
    value: 1,
    color: "brown",
    rent: { 1: 1, 2: 2 }, // Rent for 1 or 2 properties
    image: "/cards/old-kent-road.png",
  },
  {
    id: "property-whitechapel-road",
    type: "property",
    name: "Whitechapel Road",
    value: 1,
    color: "brown",
    rent: { 1: 1, 2: 2 },
    image: "/cards/whitechapel-road.png",
  },
  // Property cards - Light Blue
  {
    id: "property-euston-road",
    type: "property",
    name: "Euston Road",
    value: 1,
    color: "light blue",
    rent: { 1: 1, 2: 2, 3: 3 }, // Rent for 1, 2 or 3 properties
    image: "/cards/euston-road.png",
  },
  {
    id: "property-pentonville-road",
    type: "property",
    name: "Pentonville Road",
    value: 1,
    color: "light blue",
    rent: { 1: 1, 2: 2, 3: 3 },
    image: "/cards/pentonville-road.png",
  },
  {
    id: "property-the-angel-islington",
    type: "property",
    name: "The Angel Islington",
    value: 1,
    color: "light blue",
    rent: { 1: 1, 2: 2, 3: 3 },
    image: "/cards/the-angel-islington.png",
  },
  // Property cards - Pink
  {
    id: "property-pall-mall",
    type: "property",
    name: "Pall Mall",
    value: 2,
    color: "pink",
    rent: { 1: 1, 2: 2, 3: 4 },
    image: "/cards/pall-mall.png",
  },
  {
    id: "property-whitehall",
    type: "property",
    name: "Whitehall",
    value: 2,
    color: "pink",
    rent: { 1: 1, 2: 2, 3: 4 },
    image: "/cards/whitehall.png",
  },
  {
    id: "property-northumberland-drive",
    type: "property",
    name: "Northumberland Drive",
    value: 2,
    color: "pink",
    rent: { 1: 1, 2: 2, 3: 4 },
    image: "/cards/northumb-drive.png",
  },
  // Property cards - Orange
  {
    id: "property-vine-street",
    type: "property",
    name: "Vine Street",
    value: 2,
    color: "orange",
    rent: { 1: 1, 2: 3, 3: 5 },
    image: "/cards/vine-street.png",
  },
  {
    id: "property-bow-street",
    type: "property",
    name: "Bow Street",
    value: 2,
    color: "orange",
    rent: { 1: 1, 2: 3, 3: 5 },
    image: "/cards/bow-street.png",
  },
  {
    id: "property-marlborough-street",
    type: "property",
    name: "Marlborough Street",
    value: 2,
    color: "orange",
    rent: { 1: 1, 2: 3, 3: 5 },
    image: "/cards/marlborough-street.png",
  },

  // Property cards - Red
  {
    id: "property-strand",
    type: "property",
    name: "Strand",
    value: 3,
    color: "red",
    rent: { 1: 2, 2: 3, 3: 6 },
    image: "/cards/strand.png",
  },
  {
    id: "property-fleet-street",
    type: "property",
    name: "Fleet Street",
    value: 3,
    color: "red",
    rent: { 1: 2, 2: 3, 3: 6 },
    image: "/cards/fleet-street.png",
  },
  {
    id: "property-trafalgar-square",
    type: "property",
    name: "Trafalgar Square",
    value: 3,
    color: "red",
    rent: { 1: 2, 2: 3, 3: 6 },
    image: "/cards/trafalgar-square.png",
  },
  // Property cards - Yellow
  {
    id: "property-piccadilly",
    type: "property",
    name: "Piccadilly",
    value: 3,
    color: "yellow",
    rent: { 1: 2, 2: 4, 3: 6 },
    image: "/cards/piccadilly.png",
  },
  {
    id: "property-leicester-square",
    type: "property",
    name: "Leicester Square",
    value: 3,
    color: "yellow",
    rent: { 1: 2, 2: 4, 3: 6 },
    image: "/cards/leicester-square.png",
  },
  {
    id: "property-coventry-street",
    type: "property",
    name: "Coventry Street",
    value: 3,
    color: "yellow",
    rent: { 1: 2, 2: 4, 3: 6 },
    image: "/cards/coventry-street.png",
  },
  // Property cards - Green
  {
    id: "property-bond-street",
    type: "property",
    name: "Bond Street",
    value: 4,
    color: "green",
    rent: { 1: 2, 2: 4, 3: 7 },
    image: "/cards/bond-street.png",
  },
  {
    id: "property-oxford-street",
    type: "property",
    name: "Oxford Street",
    value: 4,
    color: "green",
    rent: { 1: 2, 2: 4, 3: 7 },
    image: "/cards/oxford-street.png",
  },
  {
    id: "property-regent-street",
    type: "property",
    name: "Regent Street",
    value: 4,
    color: "green",
    rent: { 1: 2, 2: 4, 3: 7 },
    image: "/cards/regent-street.png",
  },
  // Property cards - Dark Blue
  {
    id: "property-park-lane",
    type: "property",
    name: "Park Lane",
    value: 4,
    color: "dark blue",
    rent: { 1: 3, 2: 8 }, // Rent for 1 or 2 properties
    image: "/cards/park-lane.png",
  },
  {
    id: "property-mayfair",
    type: "property",
    name: "Mayfair",
    value: 4,
    color: "dark blue",
    rent: { 1: 3, 2: 8 },
    image: "/cards/mayfair.png",
  },
  // Property cards - Black
  {
    id: "station-kings-cross-station",
    type: "property",
    name: "King's Cross Station",
    value: 2,
    color: "black",
    rent: { 1: 1, 2: 2, 3: 3, 4: 4 }, // Rent for 1, 2, 3 or 4 properties
    image: "/cards/kings-cross-station.png",
  },
  {
    id: "station-marylebone-station",
    type: "property",
    name: "Marylebone Station",
    value: 2,
    color: "black",
    rent: { 1: 1, 2: 2, 3: 3, 4: 4 },
    image: "/cards/marylebone-station.png",
  },
  {
    id: "station-fenchurch-street-station",
    type: "property",
    name: "Fenchurch St. Station",
    value: 2,
    color: "black",
    rent: { 1: 1, 2: 2, 3: 3, 4: 4 },
    image: "/cards/fenchurch-st-station.png",
  },
  {
    id: "station-liverpool-street-station",
    type: "property",
    name: "Liverpool St. Station",
    value: 2,
    color: "black",
    rent: { 1: 1, 2: 2, 3: 3, 4: 4 },
    image: "/cards/liverpool-st-station.png",
  },
  // Utility cards
  {
    id: "utilities-electric-company",
    type: "property",
    name: "Electric Company",
    value: 2,
    color: "mint",
    rent: { 1: 1, 2: 2 }, // Rent for 1, 2 properties
    image: "/cards/electric-company.png",
  },
  {
    id: "utilities-water-works",
    type: "property",
    name: "Water Works",
    value: 2,
    color: "mint",
    rent: { 1: 1, 2: 2 }, // Rent for 1, 2 properties
    image: "/cards/water-works.png",
  },
  // Wildcards
  {
    id: "wildcard-orange-pink-1",
    type: "wildcard",
    name: "Wild Property",
    value: 2,
    color: "orange",
    secondaryColor: "pink",
    rent: { orange: { 1: 1, 2: 3, 3: 5 }, pink: { 1: 1, 2: 2, 3: 4 } },
    image: "/cards/orange-pink-wild-property.png",
  },
  {
    id: "wildcard-orange-pink-2",
    type: "wildcard",
    name: "Wild Property",
    value: 2,
    color: "orange",
    secondaryColor: "pink",
    rent: { orange: { 1: 1, 2: 3, 3: 5 }, pink: { 1: 1, 2: 2, 3: 4 } },
    image: "/cards/orange-pink-wild-property.png",
  },
  {
    id: "wildcard-red-yellow-1",
    type: "wildcard",
    name: "Wild Property",
    value: 3,
    color: "yellow",
    secondaryColor: "red",
    rent: { yellow: { 1: 2, 2: 4, 3: 6 }, red: { 1: 2, 2: 3, 3: 6 } },
    image: "/cards/yellow-red-wild-property.png",
  },
  {
    id: "wildcard-red-yellow-2",
    type: "wildcard",
    name: "Wild Property",
    value: 3,
    color: "yellow",
    secondaryColor: "red",
    rent: { yellow: { 1: 2, 2: 4, 3: 6 }, red: { 1: 2, 2: 3, 3: 6 } },
    image: "/cards/yellow-red-wild-property.png",
  },
  {
    id: "wildcard-dark-blue-green-1",
    type: "wildcard",
    name: "Wild Property",
    value: 4,
    color: "green",
    secondaryColor: "dark blue",
    rent: { green: { 1: 2, 2: 4, 3: 7 }, "dark blue": { 1: 3, 2: 8 } },
    image: "/cards/green-blue-wild-property.png",
  },
  {
    id: "wildcard-black-green-1",
    type: "wildcard",
    name: "Wild Property",
    value: 4,
    color: "black",
    secondaryColor: "green",
    rent: { black: { 1: 1, 2: 2, 3: 3, 4: 4 }, green: { 1: 2, 2: 4, 3: 7 } },
    image: "/cards/black-green-wild-property.png",
  },
  {
    id: "wildcard-black-light-blue-1",
    type: "wildcard",
    name: "Wild Property",
    value: 2,
    color: "black",
    secondaryColor: "light blue",
    rent: {
      black: { 1: 1, 2: 2, 3: 3, 4: 4 },
      "light blue": { 1: 1, 2: 2, 3: 3 },
    },
    image: "/cards/black-light-blue-wild-property.png",
  },
  {
    id: "wildcard-black-mint-1",
    type: "wildcard",
    name: "Wild Property",
    value: 2,
    color: "black",
    secondaryColor: "mint",
    rent: { black: { 1: 1, 2: 2, 3: 3, 4: 4 }, mint: { 1: 1, 2: 2 } },
    image: "/cards/black-mint-wild-property.png",
  },
  {
    id: "wildcard-brown-light-blue-1",
    type: "wildcard",
    name: "Wild Property",
    value: 1,
    color: "brown",
    secondaryColor: "light blue",
    rent: { brown: { 1: 1, 2: 2 }, mint: { 1: 1, 2: 2 } },
    image: "/cards/brown-light-blue-wild-property.png",
  },
  {
    id: "wildcard-any-1",
    type: "wildcard",
    name: "Any Color Wildcard",
    value: 0,
    color: "any",
    image: "/cards/wild-property.png",
  },
  {
    id: "wildcard-any-2",
    type: "wildcard",
    name: "Any Color Wildcard",
    value: 0,
    color: "any",
    image: "/cards/wild-property.png",
  },
  {
    id: "action-debt-collector-1",
    type: "action",
    name: "Debt Collector",
    value: 3,
    actionType: "debt-collector",
    image: "/cards/debt-collector.png",
  },
  {
    id: "action-debt-collector-2",
    type: "action",
    name: "Debt Collector",
    value: 3,
    actionType: "debt-collector",
    image: "/cards/debt-collector.png",
  },
  {
    id: "action-debt-collector-3",
    type: "action",
    name: "Debt Collector",
    value: 3,
    actionType: "debt-collector",
    image: "/cards/debt-collector.png",
  },
  {
    id: "action-birthday-1",
    type: "action",
    name: "It's My Birthday",
    value: 2,
    actionType: "birthday",
    image: "/cards/birthday.png",
  },
  {
    id: "action-birthday-2",
    type: "action",
    name: "It's My Birthday",
    value: 2,
    actionType: "birthday",
    image: "/cards/birthday.png",
  },
  {
    id: "action-birthday-3",
    type: "action",
    name: "It's My Birthday",
    value: 2,
    actionType: "birthday",
    image: "/cards/birthday.png",
  },
  {
    id: "action-pass-go-1",
    type: "action",
    name: "Pass Go",
    value: 1,
    actionType: "pass-go",
    image: "/cards/pass-go.png",
  },
  {
    id: "action-pass-go-2",
    type: "action",
    name: "Pass Go",
    value: 1,
    actionType: "pass-go",
    image: "/cards/pass-go.png",
  },
  {
    id: "action-pass-go-3",
    type: "action",
    name: "Pass Go",
    value: 1,
    actionType: "pass-go",
    image: "/cards/pass-go.png",
  },
  {
    id: "action-pass-go-4",
    type: "action",
    name: "Pass Go",
    value: 1,
    actionType: "pass-go",
    image: "/cards/pass-go.png",
  },
  {
    id: "action-pass-go-5",
    type: "action",
    name: "Pass Go",
    value: 1,
    actionType: "pass-go",
    image: "/cards/pass-go.png",
  },
  {
    id: "action-pass-go-6",
    type: "action",
    name: "Pass Go",
    value: 1,
    actionType: "pass-go",
    image: "/cards/pass-go.png",
  },
  {
    id: "action-pass-go-7",
    type: "action",
    name: "Pass Go",
    value: 1,
    actionType: "pass-go",
    image: "/cards/pass-go.png",
  },
  {
    id: "action-pass-go-8",
    type: "action",
    name: "Pass Go",
    value: 1,
    actionType: "pass-go",
    image: "/cards/pass-go.png",
  },
  {
    id: "action-pass-go-9",
    type: "action",
    name: "Pass Go",
    value: 1,
    actionType: "pass-go",
    image: "/cards/pass-go.png",
  },
  {
    id: "action-pass-go-10",
    type: "action",
    name: "Pass Go",
    value: 1,
    actionType: "pass-go",
    image: "/cards/pass-go.png",
  },
  {
    id: "action-deal-breaker-1",
    type: "action",
    name: "Deal Breaker",
    value: 5,
    actionType: "deal-breaker",
    image: "/cards/deal-breaker.png",
  },
  {
    id: "action-deal-breaker-2",
    type: "action",
    name: "Deal Breaker",
    value: 5,
    actionType: "deal-breaker",
    image: "/cards/deal-breaker.png",
  },
  {
    id: "action-sly-deal-1",
    type: "action",
    name: "Sly Deal",
    value: 3,
    actionType: "sly-deal",
    image: "/cards/sly-deal.png",
  },
  {
    id: "action-sly-deal-2",
    type: "action",
    name: "Sly Deal",
    value: 3,
    actionType: "sly-deal",
    image: "/cards/sly-deal.png",
  },
  {
    id: "action-sly-deal-3",
    type: "action",
    name: "Sly Deal",
    value: 3,
    actionType: "sly-deal",
    image: "/cards/sly-deal.png",
  },
  {
    id: "action-forced-deal-1",
    type: "action",
    name: "Forced Deal",
    value: 3,
    actionType: "forced-deal",
    image: "/cards/forced-deal.png",
  },
  {
    id: "action-forced-deal-2",
    type: "action",
    name: "Forced Deal",
    value: 3,
    actionType: "forced-deal",
    image: "/cards/forced-deal.png",
  },
  {
    id: "action-forced-deal-3",
    type: "action",
    name: "Forced Deal",
    value: 3,
    actionType: "forced-deal",
    image: "/cards/forced-deal.png",
  },
  {
    id: "action-just-say-no-1",
    type: "action",
    name: "Just Say No",
    value: 4,
    actionType: "just-say-no",
    image: "/cards/just-say-no.png",
  },
  {
    id: "action-just-say-no-2",
    type: "action",
    name: "Just Say No",
    value: 4,
    actionType: "just-say-no",
    image: "/cards/just-say-no.png",
  },
  {
    id: "action-just-say-no-3",
    type: "action",
    name: "Just Say No",
    value: 4,
    actionType: "just-say-no",
    image: "/cards/just-say-no.png",
  },
  {
    id: "action-rent-brown-light-blue-1",
    type: "action",
    name: "Rent: Brown/Light Blue",
    value: 1,
    actionType: "rent",
    color: "brown",
    secondaryColor: "light blue",
    image: "/cards/rent-brown-or-light-blue.png",
  },
  {
    id: "action-rent-brown-light-blue-2",
    type: "action",
    name: "Rent: Brown/Light Blue",
    value: 1,
    actionType: "rent",
    color: "brown",
    secondaryColor: "light blue",
    image: "/cards/rent-brown-or-light-blue.png",
  },
  {
    id: "action-rent-pink-orange-1",
    type: "action",
    name: "Rent: Pink/Orange",
    value: 1,
    actionType: "rent",
    color: "pink",
    secondaryColor: "orange",
    image: "/cards/rent-pink-or-orange.png",
  },
  {
    id: "action-rent-pink-orange-2",
    type: "action",
    name: "Rent: Pink/Orange",
    value: 1,
    actionType: "rent",
    color: "pink",
    secondaryColor: "orange",
    image: "/cards/rent-pink-or-orange.png",
  },
  {
    id: "action-rent-red-yellow-1",
    type: "action",
    name: "Rent: Red/Yellow",
    value: 1,
    actionType: "rent",
    color: "red",
    secondaryColor: "yellow",
    image: "/cards/rent-red-or-yellow.png",
  },
  {
    id: "action-rent-red-yellow-2",
    type: "action",
    name: "Rent: Red/Yellow",
    value: 1,
    actionType: "rent",
    color: "red",
    secondaryColor: "yellow",
    image: "/cards/rent-red-or-yellow.png",
  },
  {
    id: "action-rent-dark-blue-green-1",
    type: "action",
    name: "Rent: Dark Blue/Green",
    value: 1,
    actionType: "rent",
    color: "dark blue",
    secondaryColor: "green",
    image: "/cards/rent-dark-blue-or-green.png",
  },
  {
    id: "action-rent-dark-blue-green-2",
    type: "action",
    name: "Rent: Dark Blue/Green",
    value: 1,
    actionType: "rent",
    color: "dark blue",
    secondaryColor: "green",
    image: "/cards/rent-dark-blue-or-green.png",
  },
  {
    id: "action-rent-mint-black-1",
    type: "action",
    name: "Rent: Mint/Black",
    value: 1,
    actionType: "rent",
    color: "mint",
    secondaryColor: "black",
    image: "/cards/rent-mint-or-black.png",
  },
  {
    id: "action-rent-mint-black-2",
    type: "action",
    name: "Rent: Mint/Black",
    value: 1,
    actionType: "rent",
    color: "mint",
    secondaryColor: "black",
    image: "/cards/rent-mint-or-black.png",
  },
  {
    id: "action-any-color-1",
    type: "action",
    name: "Rent: Any",
    value: 3,
    actionType: "rent",
    color: "any",
    image: "/cards/rent-any-colour.png",
  },
  {
    id: "action-any-color-2",
    type: "action",
    name: "Rent: Any",
    value: 3,
    actionType: "rent",
    color: "any",
    image: "/cards/rent-any-colour.png",
  },
  {
    id: "action-any-color-3",
    type: "action",
    name: "Rent: Any",
    value: 3,
    actionType: "rent",
    color: "any",
    image: "/cards/rent-any-colour.png",
  },
  // double the rent cards
  {
    id: "double the rent-1",
    type: "action",
    name: "Double the Rent",
    value: 1,
    actionType: "double-the-rent",
    image: "/cards/double-rent.png",
  },
  {
    id: "double the rent-2",
    type: "action",
    name: "Double the Rent",
    value: 1,
    actionType: "double-the-rent",
    image: "/cards/double-rent.png",
  },
  // House and Hotel cards
  {
    id: "house-1",
    type: "action",
    name: "House",
    value: 3,
    image: "/cards/house.png",
  },
  {
    id: "house-2",
    type: "action",
    name: "House",
    value: 3,
    image: "/cards/house.png",
  },
  {
    id: "house-3",
    type: "action",
    name: "House",
    value: 3,
    image: "/cards/house.png",
  },
  {
    id: "hotel-1",
    type: "action",
    name: "Hotel",
    value: 4,
    image: "/cards/hotel.png",
  },
  {
    id: "hotel-2",
    type: "action",
    name: "Hotel",
    value: 4,
    image: "/cards/hotel.png",
  },
];

console.log("Total cards in cardDataaaaa:", cardData.length);
